import XCTest

@testable import FluidAudio

/// Bit-level parity tests for `MagpieMT19937` against NumPy's MT19937.
///
/// All ground-truth values were generated by `np.random.seed(N)` followed by
/// the corresponding NumPy call (see `Tests/.../MagpieMT19937Tests.swift`
/// docstring per test). Any change to the seeding or recurrence will be
/// caught by an exact integer / hex-bit double mismatch.
final class MagpieMT19937Tests: XCTestCase {

    // MARK: - State vector parity

    /// `np.random.seed(42); np.random.get_state()[1][:10]`
    func testStateAfterSeed42() {
        let mt = MagpieMT19937(seed: 42)
        let expected: [UInt32] = [
            42,
            3_107_752_595,
            1_895_908_407,
            3_900_362_577,
            3_030_691_166,
            4_081_230_161,
            2_732_361_568,
            1_361_238_961,
            3_961_642_104,
            867_618_704,
        ]
        let actual = mt._stateForTesting(count: expected.count)
        XCTAssertEqual(actual, expected)
    }

    /// `np.random.seed(0); np.random.get_state()[1][:3]`
    func testStateAfterSeed0() {
        let mt = MagpieMT19937(seed: 0)
        let expected: [UInt32] = [0, 1, 1_812_433_255]
        let actual = mt._stateForTesting(count: expected.count)
        XCTAssertEqual(actual, expected)
    }

    // MARK: - Uniform double parity

    /// `np.random.seed(42); np.random.random_sample(5)`
    func testUniformDoubleSeed42() {
        let mt = MagpieMT19937(seed: 42)
        let expected: [Double] = [
            0.374_540_118_847_362_5,
            0.950_714_306_409_916_2,
            0.731_993_941_811_405_1,
            0.598_658_484_197_036_6,
            0.156_018_640_442_436_52,
        ]
        for i in 0..<expected.count {
            let got = mt.uniformDouble()
            // NumPy returns IEEE-754 fp64; expect bit-exact match.
            XCTAssertEqual(
                got.bitPattern, expected[i].bitPattern,
                "random_sample()[\(i)]: got \(got), expected \(expected[i])")
        }
    }

    /// `np.random.seed(0); np.random.random_sample(3)`
    func testUniformDoubleSeed0() {
        let mt = MagpieMT19937(seed: 0)
        let expected: [Double] = [
            0.548_813_503_927_324_8,
            0.715_189_366_372_419_5,
            0.602_763_376_071_643_9,
        ]
        for i in 0..<expected.count {
            let got = mt.uniformDouble()
            XCTAssertEqual(got.bitPattern, expected[i].bitPattern)
        }
    }

    // MARK: - numpyChoice parity

    /// `np.random.seed(42); [np.random.choice(5, p=[.1,.2,.3,.25,.15]) for _ in range(20)]`
    func testNumpyChoiceWeightedSeed42() {
        let mt = MagpieMT19937(seed: 42)
        let probs: [Double] = [0.1, 0.2, 0.3, 0.25, 0.15]
        let expected: [Int] = [
            2, 4, 3, 2, 1, 1, 0, 4, 3, 3, 0, 4, 3, 1, 1, 1, 2, 2, 2, 1,
        ]
        for i in 0..<expected.count {
            let got = mt.numpyChoice(probs: probs)
            XCTAssertEqual(got, expected[i], "draw \(i) mismatch")
        }
    }

    /// `np.random.seed(0); [np.random.choice(20, p=[1/20]*20) for _ in range(10)]`
    func testNumpyChoiceUniformSeed0() {
        let mt = MagpieMT19937(seed: 0)
        let probs = [Double](repeating: 0.05, count: 20)
        let expected: [Int] = [10, 14, 12, 10, 8, 12, 8, 17, 19, 7]
        for i in 0..<expected.count {
            let got = mt.numpyChoice(probs: probs)
            XCTAssertEqual(got, expected[i], "draw \(i) mismatch")
        }
    }

    // MARK: - Float-overload sanity (sampler path)

    /// The sampler hands fp32 probability vectors to the RNG. The fp32
    /// `MagpieSamplerRng.numpyChoice(probs:)` should still match NumPy when
    /// the probabilities are exactly representable in fp32.
    func testSamplerRngMatchesNumpyChoiceForExactFp32Probs() {
        // Exactly representable fp32 values (powers of 2 inverses).
        let probs32: [Float] = [0.5, 0.25, 0.125, 0.0625, 0.0625]
        let probs64: [Double] = probs32.map { Double($0) }

        // Reference uses MT19937 directly with fp64 probs.
        let referenceMt = MagpieMT19937(seed: 12_345)
        var referenceDraws: [Int] = []
        for _ in 0..<32 {
            referenceDraws.append(referenceMt.numpyChoice(probs: probs64))
        }

        // Sampler RNG goes through the fp32 path with the same seed.
        let samplerRng = MagpieSamplerRng(seed: 12_345)
        var samplerDraws: [Int] = []
        for _ in 0..<32 {
            samplerDraws.append(samplerRng.numpyChoice(probs: probs32))
        }

        XCTAssertEqual(samplerDraws, referenceDraws)
    }

    // MARK: - Determinism (independent of NumPy)

    func testTwoInstancesWithSameSeedProduceSameSequence() {
        let a = MagpieMT19937(seed: 0xDEAD_BEEF)
        let b = MagpieMT19937(seed: 0xDEAD_BEEF)
        for _ in 0..<1_000 {
            XCTAssertEqual(a.genrandInt32(), b.genrandInt32())
        }
    }

    func testDifferentSeedsDiverge() {
        let a = MagpieMT19937(seed: 1)
        let b = MagpieMT19937(seed: 2)
        var diff = 0
        for _ in 0..<256 {
            if a.genrandInt32() != b.genrandInt32() { diff += 1 }
        }
        XCTAssertGreaterThan(diff, 200, "different seeds should diverge in nearly every draw")
    }
}
