name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

  build-ios:
    name: Build (iOS)
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform support
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          sudo xcodebuild -downloadPlatform iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme FluidAudio \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            build

  build-example:
    name: Build FluidAudioExample (macOS & iOS)
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build FluidAudioExample (macOS)
        working-directory: Examples/Swift/FluidAudioExample
        run: swift build

      - name: Install iOS platform support
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          sudo xcodebuild -downloadPlatform iOS

      - name: Build FluidAudioExample (iOS)
        working-directory: Examples/Swift/FluidAudioExample
        run: |
          xcodebuild \
            -workspace .swiftpm/xcode/package.xcworkspace \
            -scheme FluidAudioExample \
            -destination 'generic/platform=iOS' \
            -derivedDataPath $PWD/.build/DerivedData \
            build
