name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15
    strategy:
      matrix:
        swift-version: ['5.10', '6.0', '6.1', '6.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

  build-ios:
    name: Build (iOS)
    runs-on: macos-15
    strategy:
      matrix:
        swift-version: ['6.1', '6.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          xcodebuild -downloadPlatform iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme FluidAudio \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            build