name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-platform-build:
    name: Cross-Platform Build Check
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      
      - name: Build for macOS
        run: |
          echo "Building for macOS..."
          swift build --product FluidAudio
      
      - name: Clean build artifacts
        run: rm -rf .build .swiftpm
      
      - name: Build for iOS
        run: |
          echo "Building for iOS..."
          xcodebuild -scheme FluidAudio \
            -sdk iphonesimulator \
            -derivedDataPath .build/ios \
            build

  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

