name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version
          ls -la Tests/

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test
        timeout-minutes: 10

  build-ios-library:
    name: Build FluidAudio Library (iOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Clean up any build artifacts
        run: |
          rm -rf .swiftpm .build
          
      - name: Build iOS library (simulator)
        run: |
          set -e
          echo "Building FluidAudio library for iOS Simulator..."
          xcodebuild -scheme FluidAudio -destination 'platform=iOS Simulator,name=Any iOS Simulator Device' build

      - name: Clean up build artifacts
        run: |
          rm -rf .swiftpm .build

      - name: Build iOS library (device)
        run: |
          set -e
          echo "Building FluidAudio library for iOS Device..."
          xcodebuild -scheme FluidAudio -destination 'platform=iOS,name=Any iOS Device' build
