name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          xcodebuild -downloadPlatform iOS

  build-ios:
    name: Build (iOS)
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          xcodebuild -downloadPlatform iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme FluidAudio \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            build
