name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

  build-ios:
    name: Build (iOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Select Xcode command line tools
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Boot iOS Simulator
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices available | grep 'iPhone' | grep -v 'unavailable' | head -n 1 | awk -F '[()]' '{print $2}')
          if [ -z "$SIMULATOR_ID" ]; then
            echo "No available iPhone simulator found."
            xcrun simctl list devices available
            exit 1
          fi
          xcrun simctl boot "$SIMULATOR_ID"
          xcrun simctl bootstatus "$SIMULATOR_ID" -b

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform support
        run: sudo xcodebuild -downloadPlatform iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme FluidAudio \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build

  build-example:
    name: Build FluidAudioExample (macOS & iOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Select Xcode command line tools
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app

      - name: Boot iOS Simulator
        run: |
          SIMULATOR_ID=$(xcrun simctl list devices available | grep 'iPhone' | grep -v 'unavailable' | head -n 1 | awk -F '[()]' '{print $2}')
          if [ -z "$SIMULATOR_ID" ]; then
            echo "No available iPhone simulator found."
            xcrun simctl list devices available
            exit 1
          fi
          xcrun simctl boot "$SIMULATOR_ID"
          xcrun simctl bootstatus "$SIMULATOR_ID" -b

      - name: Build FluidAudioExample (macOS)
        working-directory: Examples/Swift/FluidAudioExample
        run: swift build

      - name: Install iOS platform support
        run: sudo xcodebuild -downloadPlatform iOS

      - name: Generate Xcode workspace
        working-directory: Examples/Swift/FluidAudioExample
        run: swift package generate-xcodeproj

      - name: Build FluidAudioExample (iOS)
        working-directory: Examples/Swift/FluidAudioExample
        run: |
          xcodebuild \
            -workspace .swiftpm/xcode/package.xcworkspace \
            -scheme FluidAudioExample \
            -destination 'generic/platform=iOS' \
            -derivedDataPath $PWD/.build/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            build
