name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

  build-and-test-macos-v2:
    name: V2 Configuration Tests (macOS)
    runs-on: macos-15
    needs: build-and-test-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Run v2-specific tests
        env:
          FLUIDAUDIO_TEST_MODEL_VERSION: v2
        run: swift test --parallel --filter TdtDecoderV2Tests
        timeout-minutes: 5

  build-ios:
    name: Build (iOS)
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Install iOS platform
        run: |
          sudo xcode-select -s /Applications/Xcode_16.app
          xcodebuild -downloadPlatform iOS

      - name: Build for iOS
        run: |
          xcodebuild -scheme FluidAudio \
            -destination 'generic/platform=iOS' \
            -derivedDataPath .build \
            build
