name: CoreML Build Compile

on:
  pull_request:
    branches: [ main ]

jobs:
  verify-coreml:
    name: Verify CoreMLDiarizerManager Builds
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Swift 6.1
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'

    - name: Build package
      run: swift build

    - name: Verify DiarizerManager runs
      run: swift test --filter testManagerBasicValidation
      timeout-minutes: 5

    - name: Run computational pipeline tests
      run: swift test --filter AccelerateFrameworkTests
      timeout-minutes: 10

    - name: Run parallel processing tests
      run: swift test --filter ParallelProcessingTests
      timeout-minutes: 10

    - name: Run Metal performance tests
      run: swift test --filter MetalPerformanceTests
      timeout-minutes: 10

    - name: Run computational pipeline integration tests
      run: swift test --filter ComputationalPipelineTests
      timeout-minutes: 15

    - name: Run performance validation tests
      run: swift test --filter PerformanceValidationTests
      timeout-minutes: 15
