name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-platform-build:
    name: Cross-Platform Build Check
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"
      
      - name: Cache iOS Platform
        uses: actions/cache@v4
        with:
          path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform
          key: ios-platform-${{ runner.os }}-xcode-${{ hashFiles('/Applications/Xcode.app/Contents/version.plist') }}
          restore-keys: |
            ios-platform-${{ runner.os }}-xcode-
      
      - name: Build for macOS
        run: |
          echo "Building for macOS..."
          swift build --product FluidAudio
      
      - name: Clean build artifacts
        run: rm -rf .build .swiftpm
      
      - name: Setup iOS SDK and Simulator
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          
          # Install iOS Simulator runtime
          echo "Installing iOS Simulator runtime..."
          sudo xcodebuild -runFirstLaunch
          
          # Download and install iOS runtime if needed
          LATEST_IOS_VERSION=$(xcodebuild -showsdks | grep "iOS " | tail -1 | sed 's/.*iOS \([0-9.]*\).*/\1/')
          echo "Latest iOS version: $LATEST_IOS_VERSION"
          
          if [ ! -z "$LATEST_IOS_VERSION" ]; then
            echo "Downloading iOS $LATEST_IOS_VERSION runtime..."
            sudo xcodebuild -downloadPlatform iOS || echo "Platform download failed, continuing..."
            
            # Wait for runtime to be available
            echo "Waiting for iOS runtime to be available..."
            for i in {1..30}; do
              if xcrun simctl list runtimes | grep -q "iOS.*$LATEST_IOS_VERSION"; then
                echo "iOS runtime is now available"
                break
              fi
              echo "Waiting... ($i/30)"
              sleep 10
            done
          fi
          
          # Verify SDKs are installed
          echo "Available SDKs:"
          xcodebuild -showsdks | grep -i ios
          
          # List available runtimes and devices
          echo "Available runtimes:"
          xcrun simctl list runtimes
          echo "Available devices:"
          xcrun simctl list devices available
          
          # Create iPhone 15 simulator if runtime is available
          LATEST_RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | tail -1 | awk '{print $(NF-1)}' | tr -d '()')
          if [ ! -z "$LATEST_RUNTIME" ]; then
            echo "Creating simulator with runtime: $LATEST_RUNTIME"
            xcrun simctl create "iPhone-15-Test" "iPhone 15" "$LATEST_RUNTIME" 2>/dev/null || echo "Simulator already exists or creation failed"
          fi
      
      - name: Build for iOS
        run: |
          echo "Building for iOS..."
          
          # Verify iOS SDK is available
          echo "Available iOS SDKs:"
          xcodebuild -showsdks | grep -i ios
          
          # List available simulators
          echo "Available simulators:"
          xcrun simctl list devices available | grep -i iphone || echo "No iPhone simulators found"
          
          # Get the first available iPhone simulator
          SIMULATOR=$(xcrun simctl list devices available | grep -i "iphone" | head -1 | sed 's/^[[:space:]]*//' | sed 's/ (.*//')
          
          if [ ! -z "$SIMULATOR" ]; then
            echo "Using simulator: $SIMULATOR"
            
            # Try building with specific simulator
            echo "Attempting iOS build with simulator: $SIMULATOR"
            if xcodebuild -scheme FluidAudio \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=$SIMULATOR" \
              -derivedDataPath .build/ios \
              build CODE_SIGNING_ALLOWED=NO \
              -allowProvisioningUpdates; then
              echo "✅ iOS build succeeded with specific simulator"
              exit 0
            fi
          fi
          
          # Fallback: Try multiple destination approaches
          echo "Trying fallback approaches..."
          
          echo "Attempting iOS build with generic destination..."
          if xcodebuild -scheme FluidAudio \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath .build/ios \
            build CODE_SIGNING_ALLOWED=NO \
            -allowProvisioningUpdates; then
            echo "✅ Generic iOS build succeeded"
          else
            echo "⚠️ Generic destination failed, trying 'Any iOS Simulator'..."
            if xcodebuild -scheme FluidAudio \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=Any iOS Simulator' \
              -derivedDataPath .build/ios \
              build CODE_SIGNING_ALLOWED=NO \
              -allowProvisioningUpdates; then
              echo "✅ 'Any iOS Simulator' build succeeded"
            else
              echo "❌ All approaches failed"
              exit 1
            fi
          fi

  build-and-test-macos:
    name: Build and Test Swift Package (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check versions
        run: |
          swift --version
          xcodebuild -version

      - name: Build package
        run: swift build

      - name: Run tests
        run: swift test --parallel --num-workers $(sysctl -n hw.ncpu)
        timeout-minutes: 10

